### ISSUE TITLE
scraped tv show still show star

### ISSUE THREAD

**Issue by AABoyz** [Komet/MediaElch#1045]
**Describe the bug**
Hello, new user having a problem, searched but can't find a similar issue. I'm really happy with the product, the very few nicks I have, have already been submitted and/or addressed. The issue I want to insert here is I have a few t.v. shows that were scraped (I wiped all prior data and inserted typos in all the episodes so the scraper does its thing with a clean slate) a few shows still show a star even though scrapped one at a time, using the TVDB code or name as the search criteria and save. reloaded the folder, same, relaunched the app same, rebooted the pc, winX, same, so here I am.

**To Reproduce**
4. See error / Crash

**Expected behavior**

**Screenshots**

**MediaElch Version:**
 - [ ] 2.6.7-dev (nightly)
 - [ ] 2.6.6 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [ ] Linux (distribution: _._)

**Additional context**

**Comment by AABoyz** [comment]
From: Andre MeyeringSent: November 10, 2020 11:00 AMTo: Komet/MediaElchCc: AABoyz; AuthorSubject: Re: [Komet/MediaElch] scraped tv show still show star (#1045) Hi,thank you for reporting this issue! I've experienced similar a behavior but didn't get to fix this, yet.Related issue: #1031—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Really no rush, just reporting, can I help? Some log or anything else? Would my pleasure, retired Veteran, have a lot of time on my hands, perfectly French(Canadian)/English bilingual btw. Mike

**Comment by bugwelle** [comment]
Hi, thanks. I already know where to look, a log won't help here. But fixing it may cause other issues so I need to refactor some code. :-/

Btw: If you find wrong/misleading translations, you can help here: https://mediaelch.github.io/mediaelch-doc/contributing/translations.html 😄

**Comment by AABoyz** [comment]
Hi André, I fixed one star problem I'll post it online in the thread I
started

Mike

**Comment by bugwelle** [comment]
It's been too long since I looked into this thread. Where did you post it? :-)

This will likely be fixed by #1072

**Comment by bugwelle** [comment]
The current nightly does not include the fix, but the next release should contain it. :-)

**Comment by AABoyz** [comment]
Thanks bud, I really do appreciate your great work. I know nothing about
coding but am quite adept at gimp, a while back while using the app, I told
myself it would be nice to have visual confirmation of when a button was
pressed. it would be quite easy I believe to make you something like that,
all you would have to do is tell me the format you require and I would be
happy to make a sample, which upon your confirmation I would make all the
buttons and whatever other visual mods you so wish, it would be my
contribution to your work, a way to say thank you I guess :)
I can do 3D buttons, complex shadows and light source in any directions as
well as the hard to do chrome, pitted metal surface or any surface, if you
can think of it, even better, give me an example, I can probably do it.
Including keeping it very clean and professionally designed as it is.

I am a fan of Star Trek and I like listening to music, I usually listen
using the Radio-Sure app (windows)
I am including a link to my personal google drive location
(Completely virus-free I just double-checked to make sure using windows
defender) which has the latest version of the app, the skin I made and a
how-to. No worries, AABoyz is me, referring to my old gaming days when I
was a Beta for the US government in their game "America's Army".

Please keep my drive link for yourself only but feel free to redistribute
the skin if you so wish, I am happy with that.

https://drive.google.com/drive/folders/1MvWcS46qS851sJaCqLlxP8jbY1qqfH3w?usp=sharing

Feel free to download and install, it is a completely free program and I
have included a link to their website for reference.

Install my skin and you will see what I can do, not much compared to what
you have done but it's what I am capable to do considering my brain damage
limitations.

Of course, it is very flashy but it is what the Borg in star trek are, very
flashy. I also made the IKF badge (the Intergalactic Kegger Fleets), which
is my fleet's logo that I made for my web site for the star trek game I
play, here's a link;
Intergalactic Kegger Fleets (wixsite.com)
<https://mikekatina.wixsite.com/intergalactic-kegger>

[image: I.K.F. Badge.png]

**Comment by JalilArfaoui** [comment]
@bugwelle I still have the issue … Some TV Shows are starred forever …
