### ISSUE TITLE
Be able to scrape TVmaze episode guest actors

### ISSUE THREAD

**Issue by kolbdog323** [Komet/MediaElch#1801]
Would it be possible to implement scraping of TVmaze episode actors since the tvmaze episode ordering is not always the same as TMDB for some shows and TVmaze sometimes has more of a complete list of episode actors then tmdb.

**Comment by bugwelle** [comment]
Thanks for the request. :)

TVMaze only has "guest cast" details for episodes, see https://www.tvmaze.com/api#episode-main-information

For example: https://api.tvmaze.com/episodes/5264?embed[]=guestcast

Regards,
Andre

**Comment by kolbdog323** [comment]
Sorry I meant add support for guest actors for TV maze not episode actors my bad

**Comment by bugwelle** [comment]
Ah, ok! Fixed via #1845

**Comment by bugwelle** [comment]
Forgot to adapt UI. See https://github.com/Komet/MediaElch/issues/1847

**Comment by kolbdog323** [comment]
Thanks for looking into this and reopening issue and just so you know the new nightly build with guest actors support does not work i tested it with the new build and here is a episode reference for you:
S05E13 - Call me Fran from the tv Series the Nanny and on the website it shows 4 episode guest stars for that episode but when you scrape it none of the guest stars are scraped.

**Comment by kolbdog323** [comment]
Yes I realzie you forgot to adapt to the UI but just letting you be reaware of the issue since you are reopening issue

**Comment by kolbdog323** [comment]
When think will get chance to fix this its been about a week since last nightly build

**Comment by kolbdog323** [comment]
Hey I am just wondering how is progress coming along with adding tvmaze episodes actors to the GUI since been three weeks since heard anything about it

**Comment by bugwelle** [comment]
Hi,

I didn't have time to look into it, hence no response. :)

With https://github.com/Komet/MediaElch/pull/1854 , I partially implement your feature request.
The issue is: we need to load _each_ episode from TvMaze as a _separate_ HTTP request. If we do that for a full show, we will run into TvMaze's rate limiting and the app may be blocked.

For now, I have implemented (and this time tested) loading of TvMaze guest actors for _single episode scraping_.
That is, if you select one or more episodes (but not shows or seasons!), MediaElch will load the episode's data, including guest actors.

For full seasons or TV shows, I need  to ensure that we don't run into TvMaze's rate limiting, first.

Regards,
Andre

**Comment by kolbdog323** [comment]
Thats fine doesnt need to be full show since i use all 3 scrapers i can manually add whatever actors are missing.

**Comment by kolbdog323** [comment]
The show and episode i tried was Helluva Shorts S01E03 -  MISSION: WEEABOO-BOO there is one guest star Monica Franco and she doesnt have a actor photo on her profile page she just has a character image for that episode. But the actor and role itself scraped just fine just no image was scraped for the character since doesnt have an actual actor photo just a character picture.

**Comment by kolbdog323** [comment]
Nevermind you did fix it my bad.

**Comment by bugwelle** [comment]
> Nevermind you did fix it my bad.

Thanks for confirming. :)
