### ISSUE TITLE
Latest Nightly Crashes on startup

### ISSUE THREAD

**Issue by nkatsidis** [Komet/MediaElch#723]
Windows 10 64bit

The latest 1/6/2019 nightly crashes on startup... 

all the latest nightlies have this bug..

I am still using the 8/3/2019 version that works without a problem.

**Comment by bugwelle** [comment]
Hi,

thanks for reporting this issue!
I know of this issue but can't do anything about it at the moment. That's because it's not an issue on our side but on Qt's (the framework we're using). There's a bug in Qt 5.12.1 that results in applications crashing. Qt 5.12.3 fixes this issue but mxe.cc's repositories have not been updated, yet (we use packages from mxe.cc for our nightlies).

I've opened an issue on github.com/mxe/mxe yesterday and this problem should be fixed by next Friday, I guess :)

Regards,
Andre

**Comment by nkatsidis** [comment]
thank you waiting anxiously :)

**Comment by bugwelle** [comment]
`mxe` has just updated their repositories and I just triggered a new build. The next nightly should be around in ~20min.
(it takes >40h for to update and rebuild all packages. Huge thanks to the mxe team! :smiley: )

**Comment by azriel84** [comment]
Just used the latest nightly build and it still crashes on start unfortunately (windows 10 all the latest updates).

**Comment by nkatsidis** [comment]
same here... latest nightly crashes (win10 64bit)

**Comment by bugwelle** [comment]
:/

Understood, thanks for reporting this issue. Then I'll have to start up my Windows machine, I guess.  :)

Regards,
Andre

**Comment by azriel84** [comment]
Thank you for your effort. If you require any additional information from us feel free to ask by all means!

**Comment by bugwelle** [comment]
It crashes as soon as I click on "TV Shows" so it's related to that. I know that that tab is quite buggy. Sorry for the inconvenience. :/

**Comment by azriel84** [comment]
The good thing, for you, is that at least it opens the app. In my and nkatsidis case, it crashes immediately after we press the .exe, we don't get to see the app's UI at all. Thanks again for your effort!

**Comment by nkatsidis** [comment]
I HAVE FOUND THE SOLUTION...... :)
the problem was the wrong libwinpthread-1.dll version....

by donwloading this version
https://osdn.net/projects/sfnet_sixtyfourbitcompiles/downloads/64bit/libwinpthread-1.dll/

mediaelch latest version runs fine :)

**Comment by nkatsidis** [comment]
just copy it to medialech directory

**Comment by azriel84** [comment]
Will test it tomorrow and report back!

**Comment by ticao2** [comment]
Great.
This case is interesting.
The file data, from the link I posted, is different from the file data of your link that you posted.
My Link does not tell if it's 32 or 64 bits. Your Link informs you that it is 64bit.
In my case it worked correctly. And in your case too.

My Link: **56.0 KB (57,379 bytes)**
https://pt.fix4dll.com/libwinpthread1_dll

Your Link: **55,8 KB (57,200 bytes)**
https://osdn.net/projects/sfnet_sixtyfourbitcompiles/downloads/64bit/libwinpthread-1.dll/

**Comment by bugwelle** [comment]
Hi,

may I ask if the latest nightly still crashes on startup? :)
If not, this issue may be related to #721 

Regards,
Andre

**Comment by nkatsidis** [comment]
i have tried latest nightly ..and havent encountered a crash yet :)

**Comment by azriel84** [comment]
Same here, no crash!

**Comment by bugwelle** [comment]
Great, thanks! :)
If there are any other issues, please let me know. I'll reopen this issue then.
